### ISSUE TITLE
It does not work anymore.

### ISSUE THREAD

**Issue by jooho2055** [3ba2ii/LeetSync#24] opened 2023-07-14 00:46 UTC
Hi, It worked a few hours ago, but now, the extension is not working :( 
I am not sure if it's because I updated Chrome or Leetcode changed the UI again. 
Could you please update the extension?
Thank you very much for your hard work. I really appreciated it.

**Comment by 3ba2ii** [comment] 2023-07-15 06:26
Hello @jooho2055, Thanks a lot for reporting that, I fixed the issue and uploaded a new version to the store, It should be fixed right now, Just update the extension and let me know if the problem is fixed or not

**Comment by jaydeep-pro** [comment] 2023-07-15 08:15
Its working guys, please have a look to this amazing extension

**Closed** 2023-07-15 08:16 UTC
