### ISSUE TITLE
it is no more working please look it

### ISSUE THREAD

**Issue by jaydeep-pro** [3ba2ii/LeetSync#26] opened 2023-07-14 16:43 UTC

**Comment by skccharan** [comment] 2023-07-14 17:33
yes its not working :-(

**Comment by 3ba2ii** [comment] 2023-07-15 06:19
Hello @jaydeep-pro, and @skccharan , Thanks a lot for reporting that, I fixed the issue and uploaded a new version to the store, It should be fixed right now, Just update the extension and let me know if the problem is fixed or not

**Comment by jaydeep-pro** [comment] 2023-07-15 08:14
> Hello @jaydeep-pro, and @skccharan , Thanks a lot for reporting that, I fixed the issue and uploaded a new version to the store, It should be fixed right now, Just update the extension and let me know if the problem is fixed or not

Thanks for your time. Its working now

**Closed** 2023-07-15 08:15 UTC

**Comment by skccharan** [comment] 2023-07-16 13:40
@3ba2ii thank you for closing the issue promptly..
